/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DungeonTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMMON_SWORD"
      | "DUNGEON_ENERGY_COST"
      | "ENERGY"
      | "EPIC_SWORD"
      | "GOLD"
      | "LEGENDARY_SWORD_1"
      | "LEGENDARY_SWORD_2"
      | "LEGENDARY_SWORD_3"
      | "LEGENDARY_SWORD_4"
      | "LEGENDARY_SWORD_5"
      | "RARE_SWORD"
      | "STARTER_PACK_ENERGY"
      | "STARTER_PACK_GOLD"
      | "TIME_REWARD_COOLDOWN"
      | "balanceOf"
      | "balanceOfBatch"
      | "claimStarterPack"
      | "claimTimeRewards"
      | "craftEpicSword"
      | "craftItem"
      | "craftLegendarySword"
      | "craftRareSword"
      | "getInventory"
      | "hasClaimedStarterPack"
      | "hasCraftedLegendary"
      | "isApprovedForAll"
      | "lastTimeRewardClaim"
      | "mintEnergy"
      | "mintGold"
      | "owner"
      | "renounceOwnership"
      | "runDungeon"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "supportsInterface"
      | "transferOwnership"
      | "uri"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalForAll"
      | "DungeonRun"
      | "ItemCrafted"
      | "OwnershipTransferred"
      | "StarterPackClaimed"
      | "TransferBatch"
      | "TransferSingle"
      | "URI"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMMON_SWORD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DUNGEON_ENERGY_COST",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ENERGY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "EPIC_SWORD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GOLD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LEGENDARY_SWORD_1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGENDARY_SWORD_2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGENDARY_SWORD_3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGENDARY_SWORD_4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGENDARY_SWORD_5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RARE_SWORD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STARTER_PACK_ENERGY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STARTER_PACK_GOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIME_REWARD_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimStarterPack",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "craftEpicSword",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "craftItem",
    values: [BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "craftLegendarySword",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "craftRareSword",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInventory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedStarterPack",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCraftedLegendary",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastTimeRewardClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintGold",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "runDungeon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "COMMON_SWORD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DUNGEON_ENERGY_COST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ENERGY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "EPIC_SWORD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GOLD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LEGENDARY_SWORD_1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGENDARY_SWORD_2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGENDARY_SWORD_3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGENDARY_SWORD_4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGENDARY_SWORD_5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RARE_SWORD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "STARTER_PACK_ENERGY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STARTER_PACK_GOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIME_REWARD_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimStarterPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "craftEpicSword",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "craftItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "craftLegendarySword",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "craftRareSword",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedStarterPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCraftedLegendary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTimeRewardClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintEnergy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintGold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "runDungeon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DungeonRunEvent {
  export type InputTuple = [
    player: AddressLike,
    lootId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [player: string, lootId: bigint, amount: bigint];
  export interface OutputObject {
    player: string;
    lootId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemCraftedEvent {
  export type InputTuple = [
    player: AddressLike,
    resultId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [player: string, resultId: bigint, amount: bigint];
  export interface OutputObject {
    player: string;
    resultId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarterPackClaimedEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DungeonToken extends BaseContract {
  connect(runner?: ContractRunner | null): DungeonToken;
  waitForDeployment(): Promise<this>;

  interface: DungeonTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMMON_SWORD: TypedContractMethod<[], [bigint], "view">;

  DUNGEON_ENERGY_COST: TypedContractMethod<[], [bigint], "view">;

  ENERGY: TypedContractMethod<[], [bigint], "view">;

  EPIC_SWORD: TypedContractMethod<[], [bigint], "view">;

  GOLD: TypedContractMethod<[], [bigint], "view">;

  LEGENDARY_SWORD_1: TypedContractMethod<[], [bigint], "view">;

  LEGENDARY_SWORD_2: TypedContractMethod<[], [bigint], "view">;

  LEGENDARY_SWORD_3: TypedContractMethod<[], [bigint], "view">;

  LEGENDARY_SWORD_4: TypedContractMethod<[], [bigint], "view">;

  LEGENDARY_SWORD_5: TypedContractMethod<[], [bigint], "view">;

  RARE_SWORD: TypedContractMethod<[], [bigint], "view">;

  STARTER_PACK_ENERGY: TypedContractMethod<[], [bigint], "view">;

  STARTER_PACK_GOLD: TypedContractMethod<[], [bigint], "view">;

  TIME_REWARD_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  claimStarterPack: TypedContractMethod<[], [void], "nonpayable">;

  claimTimeRewards: TypedContractMethod<[], [void], "nonpayable">;

  craftEpicSword: TypedContractMethod<[], [void], "nonpayable">;

  craftItem: TypedContractMethod<
    [
      burnIds: BigNumberish[],
      burnAmounts: BigNumberish[],
      resultId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  craftLegendarySword: TypedContractMethod<
    [legendaryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  craftRareSword: TypedContractMethod<[], [void], "nonpayable">;

  getInventory: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        energy: bigint;
        gold: bigint;
        commonSword: bigint;
        rareSword: bigint;
        epicSword: bigint;
      }
    ],
    "view"
  >;

  hasClaimedStarterPack: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  hasCraftedLegendary: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lastTimeRewardClaim: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  mintEnergy: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintGold: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  runDungeon: TypedContractMethod<[], [void], "nonpayable">;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uri: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMMON_SWORD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DUNGEON_ENERGY_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENERGY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EPIC_SWORD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEGENDARY_SWORD_1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEGENDARY_SWORD_2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEGENDARY_SWORD_3"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEGENDARY_SWORD_4"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEGENDARY_SWORD_5"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RARE_SWORD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTER_PACK_ENERGY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTER_PACK_GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIME_REWARD_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimStarterPack"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "craftEpicSword"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "craftItem"
  ): TypedContractMethod<
    [
      burnIds: BigNumberish[],
      burnAmounts: BigNumberish[],
      resultId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "craftLegendarySword"
  ): TypedContractMethod<[legendaryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "craftRareSword"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getInventory"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        energy: bigint;
        gold: bigint;
        commonSword: bigint;
        rareSword: bigint;
        epicSword: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedStarterPack"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasCraftedLegendary"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastTimeRewardClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintEnergy"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintGold"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "runDungeon"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uri"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "DungeonRun"
  ): TypedContractEvent<
    DungeonRunEvent.InputTuple,
    DungeonRunEvent.OutputTuple,
    DungeonRunEvent.OutputObject
  >;
  getEvent(
    key: "ItemCrafted"
  ): TypedContractEvent<
    ItemCraftedEvent.InputTuple,
    ItemCraftedEvent.OutputTuple,
    ItemCraftedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StarterPackClaimed"
  ): TypedContractEvent<
    StarterPackClaimedEvent.InputTuple,
    StarterPackClaimedEvent.OutputTuple,
    StarterPackClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "URI"
  ): TypedContractEvent<
    URIEvent.InputTuple,
    URIEvent.OutputTuple,
    URIEvent.OutputObject
  >;

  filters: {
    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "DungeonRun(address,uint256,uint256)": TypedContractEvent<
      DungeonRunEvent.InputTuple,
      DungeonRunEvent.OutputTuple,
      DungeonRunEvent.OutputObject
    >;
    DungeonRun: TypedContractEvent<
      DungeonRunEvent.InputTuple,
      DungeonRunEvent.OutputTuple,
      DungeonRunEvent.OutputObject
    >;

    "ItemCrafted(address,uint256,uint256)": TypedContractEvent<
      ItemCraftedEvent.InputTuple,
      ItemCraftedEvent.OutputTuple,
      ItemCraftedEvent.OutputObject
    >;
    ItemCrafted: TypedContractEvent<
      ItemCraftedEvent.InputTuple,
      ItemCraftedEvent.OutputTuple,
      ItemCraftedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StarterPackClaimed(address)": TypedContractEvent<
      StarterPackClaimedEvent.InputTuple,
      StarterPackClaimedEvent.OutputTuple,
      StarterPackClaimedEvent.OutputObject
    >;
    StarterPackClaimed: TypedContractEvent<
      StarterPackClaimedEvent.InputTuple,
      StarterPackClaimedEvent.OutputTuple,
      StarterPackClaimedEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "URI(string,uint256)": TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
  };
}
